# Use postgres/example user/password credentials
services:

  db:
    image: postgres:14.15-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD: localpassword
      POSTGRES_USER: admin
    ports:
      - 5432:5432

#  keycloak:
#    image: quay.io/keycloak/keycloak:26.1.4
#    restart: always
#    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#    command:
#      - start-dev
#    ports:
#      - 8080:8080

#  api:
#    build:
#      context: .
#      dockerfile: apps/expense_tracker/Dockerfile
#    image: expense-tracker/api:dev
#    restart: unless-stopped
#    environment:
#      RUST_LOG: info
#      # Uncomment to disable TLS validation when talking to Keycloak in dev
#      # EXPENSE_TRACKER_IGNORE_TLS: "1"
#    volumes:
#      - ./config/settings.toml:/app/config/settings.toml:ro
#    depends_on:
#      - db
#      - keycloak
#    ports:
#      - 3001:3001

#  web:
#    build:
#      context: .
#      dockerfile: apps/expense-tracker-frontend/Dockerfile
#      args:
#        NEXT_PUBLIC_API_URL: http://localhost:3001
#    image: expense-tracker/web:dev
#    restart: unless-stopped
#    environment:
#      NODE_ENV: production
#      NEXT_PUBLIC_API_URL: http://localhost:3001
#    depends_on:
#      - api
#    ports:
#      - 3000:3000