# Use postgres/example user/password credentials
services:
  db:
    image: postgres:18.1-alpine3.23
    restart: always
    environment:
      POSTGRES_PASSWORD: localpassword
      POSTGRES_USER: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432

  db-keycloak:
    image: postgres:18.1-alpine3.23
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: localpassword
      POSTGRES_USER: admin
    volumes:
      - ./postgres-data-keycloak:/var/lib/postgresql
    ports:
      - 15000:5432

  ## TODO: setup client expense-tracker in keycloak at http://localhost:8080/admin/master/console/
  ## if for some reason keycloak claims that HTTPS is required: Restart your Docker Engine and try again.
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: localpassword
      KC_DB_URL: jdbc:postgresql://db-keycloak/keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: host.docker.internal
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    command:
      - start-dev
    ports:
      - 8080:8080
    depends_on:
      - db-keycloak

  api:
    build:
      context: .
      dockerfile: apps/expense_tracker/Dockerfile
    restart: unless-stopped
    environment:
      RUST_LOG: info
      # Comment or set to 0 to enable TLS validation when talking to Keycloak in Prod
      EXPENSE_TRACKER_IGNORE_TLS: "1"
    ports:
      - 3001:3001
    volumes:
      - ./config/settings_compose.toml:/app/config/settings.toml:ro
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: apps/expense-tracker-frontend/Dockerfile
      args:
        NODE_ENV: development
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - apps/expense-tracker-frontend/.env.compose
    depends_on:
      - api