[package]
name = "expense-tracker-db"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2"
diesel-async = { version = "0.5", features = ["postgres", "bb8"] }
serde = { version = "1.0.216", features = ["derive"] }
