[package]
name = "expense-tracker-db"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2"
deadpool-diesel = { version = "0.6.1", features = ["postgres"] }
diesel_migrations = "2"
serde = { version = "1.0.216", features = ["derive"] }
