[package]
name = "expense-tracker-db"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.2"
diesel-async = { version = "0.5.2", features = ["postgres", "pool", "deadpool"] }
diesel_migrations = "2.2"
serde = { version = "1.0.216", features = ["derive"] }
