[oidc]
issuer_url = "http://host.docker.internal:8080/realms/local"
audience = "expense-tracker"

[expense_tracker]
port = 3001
db_connection_string = "postgres://admin:localpassword@db/postgres"
cors_url="http://localhost:3000"
