[oidc]
issuer_url = "https://nas.cielcat.ch:8443/realms/dev"
audience = "expense-tracker-local-dev"

[expense_tracker]
port = 3001
db_connection_string = "postgres://admin:localpassword@localhost/postgres"
cors_url="http://localhost:3000"
