[oidc]
issuer_url = "http://127.0.0.1:8080/realms/local"
audience = "expense-tracker"

[expense_tracker]
port = 3001
db_connection_string = "postgres://admin:localpassword@db/postgres"
cors_url="http://127.0.0.1:3000"
