[package]
name = "expense-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
expense-tracker-api = { path = "../expense-tracker-api" }
expense-tracker-db = { path = "../expense-tracker-db" }
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
utoipa-swagger-ui = { version = "9", features = ["axum"] }
utoipa = "5.2.0"
utoipa-axum = "0.2.0"