name: CI

on:
  pull_request:
    branches: [ master ]
  merge_group:
    types: [ checks_requested ]

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run backend tests
        run: |
          cargo test

  backend:
    name: Build backend image
    runs-on: [ubuntu-latest]
    steps:
      - name: Build backend image
        run: |
          docker build -f apps/expense_tracker/Dockerfile .

  frontend:
    name: Build frontend image
    runs-on: [ubuntu-latest]
    steps:
      - name: Build frontend image
        run: |
          docker build -f apps/expense-tracker-frontend/Dockerfile .

