name: CI

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  actions: read
  contents: read

jobs:
  # Skip the entire job on direct pushes to master
  if: github.event_name != 'push'
  main:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Run backend tests
        run: |
          cargo test

      - name: Build backend image
        run: |
          docker build -f apps/expense_tracker/Dockerfile .

      - name: Build frontend image
        run: |
          docker build -f apps/expense-tracker-frontend/Dockerfile .

